apiVersion: v1
kind: Pod
metadata:
  name: process-pod
spec:
  containers:
    - name: alpine
      image: alpine:3.20
      resources:
        limits:
          memory: "512Mi"
          cpu: "2"
      command: ["/bin/sh"]
      args: ["-c", "/app/process/entrypoint.sh"]
      volumeMounts:
        - mountPath: /app
          name: demo1-volume
      workingDir: /app
      env:
        - name: RABBITMQ_SERVICE_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
  volumes:
    - name: demo1-volume
      hostPath:
        path: /demo1
        type: Directory
