apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
    - name: web
      port: 8000
      targetPort: 8000
      nodePort: 30080
      protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  labels:
    app: web
spec:
  containers:
    - name: alpine
      image: alpine:3.20
      resources:
        limits:
          memory: "3Gi"
          cpu: "2"
      command: ["/bin/sh"]
      args: ["-c", "/app/web/entrypoint.sh"]
      volumeMounts:
        - mountPath: /app
          name: demo1-volume
      ports:
        - containerPort: 8000
      env:
        - name: RABBITMQ_SERVICE_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
  volumes:
    - name: demo1-volume
      hostPath:
        path: /demo1
        type: Directory
